### ISSUE TITLE
Hide/Unhide Window does not work

### ISSUE THREAD

**Issue by FjellOverflow** [archcraft-os/archcraft-bspwm#4]
The combinaton **MOD** + **SHIFT** + **i** is supposed to hide/unhide the focused window. It does not. In fact, the command "_winmask_" can't even be found.

My .config/bspwm/sxhkdrc contains the line:

```bash
# Hide/Unhide Window
super + shift + i
	winmask	
```

**Comment by AndyNotfound** [comment]
Yeah same here, I thought I'm the only one with this problem

**Comment by adi1090x** [comment]
Fixed.
