### ISSUE TITLE
2 Bugs with Rofi menus

### ISSUE THREAD

**Issue by PSGrobet** [archcraft-os/archcraft-bspwm#9]
Hi! I'm loving the distro. I just wanted to comment a couple of things I've found, not too big, but somewhat annoying.
1: When I press Mod+x to bring up the power menu, if I click on the icon to power off with the mouse, the confirmation dialogue appears briefly on the screen and disappears. If I click and hold and move the mouse over that window before releasing, it stays; or if I select the power off icon with the keyboard arrows and press enter, there is no problem.
2: If I open the main menu with Mod and try to type anything to search, both on the main tab as well as on the other tabs, the keyboard layout is the default US layout, not my configured layout. This is not the case if I open other rofi menus with their shortcut like the the rofi-runner, or windows menu.

Hope this helps. Cheers!

**Comment by adi1090x** [comment]
These are not bugs but limited functionalities of rofi. 
1. Rofi's selection are meant to be used by keyboard, So press Enter
2. Rofi doesn't support keyboard layouts very well, it's a known issue with upstream rofi.
